image: registry.sensetime.com/eig-research/pytorch:pytorch1.3.1-cuda10.1-devel

stages:
    - linting
    - test

before_script:
  - echo $PATH
  - gcc --version
  - nvcc --version
  - python --version
  - pip --version
  - python -c "import torch; print(torch.__version__)"

linting:
  stage: linting
  script:
    - pip install flake8 yapf isort
    - flake8 .
    - isort -rc --check-only --diff mmedit/ tools/ tests/
    - yapf -r -d mmedit/ tools/ tests/ configs/

test:
  stage: test
  script:
    - echo "Start building..."
    - pip install pillow==6.2.2
    - pip install -e .
    - python -c "import mmedit; print(mmedit.__version__)"
    - echo "Start testing..."
    - pip install pytest coverage
    - coverage run --source mmedit -m pytest tests/
    - coverage report -m
