image: registry.sensetime.com/eig-research/pytorch:1.3.1-cuda10.1-cudnn7-devel

stages:
  - linting
  - test
  - deploy

before_script:
  - echo $PATH
  - gcc --version
  - nvcc --version
  - python --version
  - pip --version
  - python -c "import torch; print(torch.__version__)"

linting:
  stage: linting
  script:
    - pip install flake8 yapf isort==4.3.21 interrogate
    - flake8 .
    - isort -rc --check-only --diff mmedit/ tools/ tests/
    - yapf -r -d mmedit/ tools/ tests/ configs/
    - interrogate -v --ignore-init-method --ignore-module --ignore-nested-functions --ignore-regex="__repr__" --fail-under 50 mmedit

test:
  stage: test
  script:
    - pip install mmcv-full
    - echo "Start building..."
    - pip install -r requirements.txt
    - pip install -e .
    - python -c "import mmedit; print(mmedit.__version__)"
    - echo "Start testing..."
    - pip install pytest coverage
    - coverage run --branch --source mmedit -m pytest tests/
    - coverage report -m

pages:
  stage: deploy
  script:
    - pip install mmcv==0.6.2
    - pip install scikit-image
    - pip install pillow==6.1.0
    - pip install sphinx sphinx_rtd_theme recommonmark sphinx-markdown-tables
    - cd docs
    - make html
    - cd ..
    - mkdir -p ./public
    - cp -r docs/_build/html/* ./public
    - ls ./public
  artifacts:
    paths:
      - public
  only:
    - master
