image: registry.sensetime.com/eig-research/pytorch:1.3.1-cuda10.1-cudnn7-devel

stages:
    - linting
    - test

before_script:
  - echo $PATH
  - gcc --version
  - nvcc --version
  - python --version
  - pip --version
  - python -c "import torch; print(torch.__version__)"

linting:
  stage: linting
  script:
    - pip install flake8 yapf isort
    - flake8 .
    - isort -rc --check-only --diff mmedit/ tools/ tests/
    - yapf -r -d mmedit/ tools/ tests/ configs/

test:
  stage: test
  script:
    - echo "Install MMCV"
    - git clone https://github.com/open-mmlab/mmcv.git
    - cd mmcv && pip install -e . && cd ..
    - echo "Start building..."
    - pip install -r requirements.txt
    - pip install -e .
    - python -c "import mmedit; print(mmedit.__version__)"
    - echo "Start testing..."
    - pip install pytest coverage
    - coverage run --branch --source mmedit -m pytest tests/
    - coverage report -m
